/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author HP
 */
public class OrderHistory extends javax.swing.JFrame {

    /**
     * Creates new form OrderHistory
     */
    public OrderHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        OrderHistoryLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        OrderNoLabel = new javax.swing.JLabel();
        EnterOrderNOText = new javax.swing.JTextField();
        CustomerNameLabel = new javax.swing.JLabel();
        EnterCustomerNameText = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        AddressText = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        ItemDetailsLabel = new javax.swing.JLabel();
        ItemsBox = new javax.swing.JComboBox<>();
        DeliveryChargesLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        RejectButton = new javax.swing.JButton();
        AcceptButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 490));

        jPanel3.setBackground(new java.awt.Color(204, 153, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 130, 490));

        OrderHistoryLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        OrderHistoryLabel.setText("Order History");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OrderHistoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OrderHistoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 480, 40));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrderNoLabel.setText("Order Number:");
        jPanel5.add(OrderNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 93, 39));

        EnterOrderNOText.setText("AB-011");
        jPanel5.add(EnterOrderNOText, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 0, 380, 39));

        CustomerNameLabel.setText("Customer Name:");
        jPanel5.add(CustomerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, 93, 33));

        EnterCustomerNameText.setText("Hello");
        EnterCustomerNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterCustomerNameTextActionPerformed(evt);
            }
        });
        jPanel5.add(EnterCustomerNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 45, 381, 33));

        AddressLabel.setText("Address:");
        jPanel5.add(AddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 84, 93, 30));

        AddressText.setText("Karachi");
        jPanel5.add(AddressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 88, 381, 32));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 480, 120));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ItemDetailsLabel.setText("Item Details:");
        jPanel6.add(ItemDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 39));

        ItemsBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2" }));
        jPanel6.add(ItemsBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, 474, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 480, 110));

        DeliveryChargesLabel.setText("Delivery Charges : Rs100/-");
        jPanel1.add(DeliveryChargesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 270, 40));

        TotalLabel.setText("Total Price: 550/-");
        jPanel1.add(TotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 140, 30));

        RejectButton.setBackground(new java.awt.Color(255, 255, 51));
        RejectButton.setText("Reject");
        jPanel1.add(RejectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 150, 40));

        AcceptButton.setBackground(new java.awt.Color(204, 153, 0));
        AcceptButton.setText("Accept");
        jPanel1.add(AcceptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterCustomerNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterCustomerNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterCustomerNameTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptButton;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressText;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JLabel DeliveryChargesLabel;
    private javax.swing.JTextField EnterCustomerNameText;
    private javax.swing.JTextField EnterOrderNOText;
    private javax.swing.JLabel ItemDetailsLabel;
    private javax.swing.JComboBox<String> ItemsBox;
    private javax.swing.JLabel OrderHistoryLabel;
    private javax.swing.JLabel OrderNoLabel;
    private javax.swing.JButton RejectButton;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
